# Generated by Django 5.2 on 2026-07-25 09:11

import abtapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoU_NO', models.CharField(max_length=100, unique=True)),
                ('ORGANIZATION_NAME', models.CharField(max_length=255)),
                ('LOCATION', models.CharField(blank=True, max_length=255, null=True)),
                ('OFFICIAL_WEBSITE', models.URLField(blank=True, null=True)),
                ('DATE_OF_MoU', models.DateField(blank=True, null=True)),
                ('VALIDITY', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=20, unique=True)),
                ('UPLOADED_DATE', models.DateField(blank=True, null=True)),
                ('TITLE', models.CharField(max_length=200)),
                ('TYPE', models.CharField(choices=[('BASICS', 'BASICS'), ('PROJECTS', 'PROJECTS'), ('PRODUCTS', 'PRODUCTS')], default=0, max_length=50)),
                ('YOUTUBE_LINK', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=abtapp.models.gallery_image_upload_path)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text="SEO alt text for this image. Example: 'Industrial Control Panel Hardware - AB Technologies'. Leave blank to auto-generate.", max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='abtapp.gallerycategory')),
            ],
        ),
    ]
