# Generated by Django 5.2 on 2026-09-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Bootstrap icon class (e.g., 'bi-laptop', 'bi-gear')", max_length=100, null=True),
        ),
    ]
