# Generated by Django 5.2 on 2026-09-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtapp', '0002_projectcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_no', models.CharField(help_text='Unique VAC Number', max_length=50, unique=True)),
                ('college_name', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('vac_title', models.CharField(max_length=255)),
                ('no_of_days', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vac_trainings', to='abtapp.gallerycategory')),
            ],
            options={
                'verbose_name': 'Value Added Course',
                'verbose_name_plural': 'Value Added Courses',
                'ordering': ['-from_date'],
            },
        ),
    ]
