# Generated by Django 5.2 on 2026-09-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtapp', '0003_vac'),
    ]

    operations = [
        migrations.AddField(
            model_name='vac',
            name='gallery_image',
            field=models.ForeignKey(blank=True, help_text='Select the specific gallery image for this VAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vac_entries', to='abtapp.galleryimage'),
        ),
    ]
