# Generated by Django 5.2 on 2026-09-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtapp', '0004_vac_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('staff_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('fund_amount', models.CharField(max_length=100)),
                ('date_of_transaction', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consultancy Project',
                'verbose_name_plural': 'Consultancy Projects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FundedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('staff_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('fund_amount', models.CharField(max_length=100)),
                ('date_of_transaction', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Funded Project',
                'verbose_name_plural': 'Funded Projects',
                'ordering': ['-id'],
            },
        ),
    ]
